SET SESSION storage_engine = "InnoDB";
SET SESSION time_zone = "+0:00";
ALTER DATABASE CHARACTER SET "utf8";

#DROP TABLE IF EXISTS sensors;
CREATE TABLE IF NOT EXISTS  sensors (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    token VARCHAR(100) NOT NULL UNIQUE,
    device_id VARCHAR(100) NOT NULL UNIQUE,
    device_key VARCHAR(100) NOT NULL,
    updated TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	sensor_id INT NOT NULL,
	datetime TIMESTAMP NOT NULL,
	text TEXT,
	json TEXT,
	FOREIGN KEY (sensor_id)
		REFERENCES sensors(id)
		ON DELETE CASCADE
);

